## Usage: Rscript {suffix} {outfile}

args <- commandArgs(TRUE)

chr1 = read.delim(paste(1, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr2 = read.delim(paste(2, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr3 = read.delim(paste(3, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr4 = read.delim(paste(4, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr5 = read.delim(paste(5, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr6 = read.delim(paste(6, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr7 = read.delim(paste(7, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr8 = read.delim(paste(8, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr9 = read.delim(paste(9, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr10 = read.delim(paste(10, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr11 = read.delim(paste(11, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr12 = read.delim(paste(12, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr13 = read.delim(paste(13, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr14 = read.delim(paste(14, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr15 = read.delim(paste(15, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr16 = read.delim(paste(16, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr17 = read.delim(paste(17, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr18 = read.delim(paste(18, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr19 = read.delim(paste(19, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr20 = read.delim(paste(20, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr21 = read.delim(paste(21, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr22 = read.delim(paste(22, args[1], ".maf", sep = ""), header = TRUE, stringsAsFactors = FALSE)

mergecolumn = names(chr1)[1]

all.maf = merge(chr1,chr2, by = mergecolumn, suffix = c(".1", ".2"), all = TRUE)
all.maf = merge(all.maf,chr3, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr4, by = mergecolumn, suffix = c(".3", ".4"), all = TRUE)
all.maf = merge(all.maf,chr5, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr6, by = mergecolumn, suffix = c(".5", ".6"), all = TRUE)
all.maf = merge(all.maf,chr7, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr8, by = mergecolumn, suffix = c(".7", ".8"), all = TRUE)
all.maf = merge(all.maf,chr9, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr10, by = mergecolumn, suffix = c(".9", ".10"), all = TRUE)
all.maf = merge(all.maf,chr11, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr12, by = mergecolumn, suffix = c(".11", ".12"), all = TRUE)
all.maf = merge(all.maf,chr13, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr14, by = mergecolumn, suffix = c(".13", ".14"), all = TRUE)
all.maf = merge(all.maf,chr15, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr16, by = mergecolumn, suffix = c(".15", ".16"), all = TRUE)
all.maf = merge(all.maf,chr17, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr18, by = mergecolumn, suffix = c(".17", ".18"), all = TRUE)
all.maf = merge(all.maf,chr19, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr20, by = mergecolumn, suffix = c(".19", ".20"), all = TRUE)
all.maf = merge(all.maf,chr21, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.maf = merge(all.maf,chr22, by = mergecolumn, suffix = c(".21", ".22"), all = TRUE)

all.maf$Mean_Info.all = ((all.maf$Mean_Info.1 * all.maf$Count.1) + (all.maf$Mean_Info.2 * all.maf$Count.2) + (all.maf$Mean_Info.3 * all.maf$Count.3) + (all.maf$Mean_Info.4 * all.maf$Count.4) + (all.maf$Mean_Info.5 * all.maf$Count.5) + (all.maf$Mean_Info.6 * all.maf$Count.6) + (all.maf$Mean_Info.7 * all.maf$Count.7) + (all.maf$Mean_Info.8 * all.maf$Count.8) + (all.maf$Mean_Info.9 * all.maf$Count.9) + (all.maf$Mean_Info.10 * all.maf$Count.10) + (all.maf$Mean_Info.11 * all.maf$Count.11) + (all.maf$Mean_Info.12 * all.maf$Count.12) + (all.maf$Mean_Info.13 * all.maf$Count.13) + (all.maf$Mean_Info.14 * all.maf$Count.14) + (all.maf$Mean_Info.15 * all.maf$Count.15) + (all.maf$Mean_Info.16 * all.maf$Count.16) + (all.maf$Mean_Info.17 * all.maf$Count.17) + (all.maf$Mean_Info.18 * all.maf$Count.18) + (all.maf$Mean_Info.19 * all.maf$Count.19) + (all.maf$Mean_Info.20 * all.maf$Count.20) + (all.maf$Mean_Info.21 * all.maf$Count.21) + (all.maf$Mean_Info.22 * all.maf$Count.22))/(all.maf$Count.1 + all.maf$Count.2 + all.maf$Count.3 + all.maf$Count.4 + all.maf$Count.5 + all.maf$Count.6 + all.maf$Count.7 + all.maf$Count.8 + all.maf$Count.9 + all.maf$Count.10 + all.maf$Count.11 + all.maf$Count.12 + all.maf$Count.13 + all.maf$Count.14 + all.maf$Count.15 + all.maf$Count.16 + all.maf$Count.17 + all.maf$Count.18 + all.maf$Count.19 + all.maf$Count.20 + all.maf$Count.21 + all.maf$Count.22)

all.maf$Count.all = (all.maf$Count.1 + all.maf$Count.2 + all.maf$Count.3 + all.maf$Count.4 + all.maf$Count.5 + all.maf$Count.6 + all.maf$Count.7 + all.maf$Count.8 + all.maf$Count.9 + all.maf$Count.10 + all.maf$Count.11 + all.maf$Count.12 + all.maf$Count.13 + all.maf$Count.14 + all.maf$Count.15 + all.maf$Count.16 + all.maf$Count.17 + all.maf$Count.18 + all.maf$Count.19 + all.maf$Count.20 + all.maf$Count.21 + all.maf$Count.22)

write.table(all.maf, file = paste(args[2], "_summary.info.maf", sep = ""), quote = FALSE, row.names = FALSE, sep = "\t", na = "NA")

jpeg(width = 6, height = 6, units = "in", res = 300, file = paste(args[2], ".info.maf.jpeg", sep = ""))
plot(x = all.maf$MAFbins, y = all.maf$Mean_Info.all, axes = FALSE, xlab = "Minor Allele Frequency", ylab = "Imputation Info Score (Mean per MAF bin)", pch = 4, type = "b", xlim = c(0,0.5), ylim = c(0,1))
axis(side = 1, labels = round(seq(0,0.5, 0.05),2), at = seq(0,0.5, 0.05))
axis(side = 2, labels = round(seq(0,1,0.1),1), at = seq(0,1,0.1))
dev.off()


### Hardy-Weinberg

chr1 = read.delim(paste(1, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr2 = read.delim(paste(2, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr3 = read.delim(paste(3, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr4 = read.delim(paste(4, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr5 = read.delim(paste(5, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr6 = read.delim(paste(6, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr7 = read.delim(paste(7, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr8 = read.delim(paste(8, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr9 = read.delim(paste(9, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr10 = read.delim(paste(10, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr11 = read.delim(paste(11, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr12 = read.delim(paste(12, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr13 = read.delim(paste(13, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr14 = read.delim(paste(14, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr15 = read.delim(paste(15, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr16 = read.delim(paste(16, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr17 = read.delim(paste(17, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr18 = read.delim(paste(18, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr19 = read.delim(paste(19, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr20 = read.delim(paste(20, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr21 = read.delim(paste(21, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)
chr22 = read.delim(paste(22, args[1], ".hwe", sep = ""), header = TRUE, stringsAsFactors = FALSE)

mergecolumn = names(chr1)[1]

all.hwe = merge(chr1,chr2, by = mergecolumn, suffix = c(".1", ".2"), all = TRUE)
all.hwe = merge(all.hwe,chr3, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr4, by = mergecolumn, suffix = c(".3", ".4"), all = TRUE)
all.hwe = merge(all.hwe,chr5, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr6, by = mergecolumn, suffix = c(".5", ".6"), all = TRUE)
all.hwe = merge(all.hwe,chr7, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr8, by = mergecolumn, suffix = c(".7", ".8"), all = TRUE)
all.hwe = merge(all.hwe,chr9, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr10, by = mergecolumn, suffix = c(".9", ".10"), all = TRUE)
all.hwe = merge(all.hwe,chr11, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr12, by = mergecolumn, suffix = c(".11", ".12"), all = TRUE)
all.hwe = merge(all.hwe,chr13, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr14, by = mergecolumn, suffix = c(".13", ".14"), all = TRUE)
all.hwe = merge(all.hwe,chr15, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr16, by = mergecolumn, suffix = c(".15", ".16"), all = TRUE)
all.hwe = merge(all.hwe,chr17, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr18, by = mergecolumn, suffix = c(".17", ".18"), all = TRUE)
all.hwe = merge(all.hwe,chr19, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr20, by = mergecolumn, suffix = c(".19", ".20"), all = TRUE)
all.hwe = merge(all.hwe,chr21, by = mergecolumn, suffix = c("", ""), all = TRUE)
all.hwe = merge(all.hwe,chr22, by = mergecolumn, suffix = c(".21", ".22"), all = TRUE)

all.hwe$Mean_Info.all = ((all.hwe$Mean_Info.1 * all.hwe$Count.1) + (all.hwe$Mean_Info.2 * all.hwe$Count.2) + (all.hwe$Mean_Info.3 * all.hwe$Count.3) + (all.hwe$Mean_Info.4 * all.hwe$Count.4) + (all.hwe$Mean_Info.5 * all.hwe$Count.5) + (all.hwe$Mean_Info.6 * all.hwe$Count.6) + (all.hwe$Mean_Info.7 * all.hwe$Count.7) + (all.hwe$Mean_Info.8 * all.hwe$Count.8) + (all.hwe$Mean_Info.9 * all.hwe$Count.9) + (all.hwe$Mean_Info.10 * all.hwe$Count.10) + (all.hwe$Mean_Info.11 * all.hwe$Count.11) + (all.hwe$Mean_Info.12 * all.hwe$Count.12) + (all.hwe$Mean_Info.13 * all.hwe$Count.13) + (all.hwe$Mean_Info.14 * all.hwe$Count.14) + (all.hwe$Mean_Info.15 * all.hwe$Count.15) + (all.hwe$Mean_Info.16 * all.hwe$Count.16) + (all.hwe$Mean_Info.17 * all.hwe$Count.17) + (all.hwe$Mean_Info.18 * all.hwe$Count.18) + (all.hwe$Mean_Info.19 * all.hwe$Count.19) + (all.hwe$Mean_Info.20 * all.hwe$Count.20) + (all.hwe$Mean_Info.21 * all.hwe$Count.21) + (all.hwe$Mean_Info.22 * all.hwe$Count.22))/(all.hwe$Count.1 + all.hwe$Count.2 + all.hwe$Count.3 + all.hwe$Count.4 + all.hwe$Count.5 + all.hwe$Count.6 + all.hwe$Count.7 + all.hwe$Count.8 + all.hwe$Count.9 + all.hwe$Count.10 + all.hwe$Count.11 + all.hwe$Count.12 + all.hwe$Count.13 + all.hwe$Count.14 + all.hwe$Count.15 + all.hwe$Count.16 + all.hwe$Count.17 + all.hwe$Count.18 + all.hwe$Count.19 + all.hwe$Count.20 + all.hwe$Count.21 + all.hwe$Count.22)

all.hwe$Count.all = (all.hwe$Count.1 + all.hwe$Count.2 + all.hwe$Count.3 + all.hwe$Count.4 + all.hwe$Count.5 + all.hwe$Count.6 + all.hwe$Count.7 + all.hwe$Count.8 + all.hwe$Count.9 + all.hwe$Count.10 + all.hwe$Count.11 + all.hwe$Count.12 + all.hwe$Count.13 + all.hwe$Count.14 + all.hwe$Count.15 + all.hwe$Count.16 + all.hwe$Count.17 + all.hwe$Count.18 + all.hwe$Count.19 + all.hwe$Count.20 + all.hwe$Count.21 + all.hwe$Count.22)

write.table(all.hwe, file = paste(args[2], "_summary.info.hwe", sep = ""), quote = FALSE, row.names = FALSE, sep = "\t", na = "NA")

jpeg(width = 6, height = 6, units = "in", res = 300, file = paste(args[2], ".info.hwe.jpeg", sep = ""))
plot(x = all.hwe$HWEbins, y = all.hwe$Mean_Info.all, axes = FALSE, xlab = "Hardy-Weinberg Equilibrium", ylab = "Imputation Info Score (Mean per HWE bin)", pch = 4, type = "b", xlim = c(0,1), ylim = c(0,1))
axis(side = 1, labels = round(seq(0, 1, 0.05),2), at = seq(0, 1, 0.05))
axis(side = 2, labels = round(seq(0, 1, 0.1),1), at = seq(0, 1, 0.1))
dev.off()
